### ISSUE TITLE
Creating relationship in model with composite keys throws “Property is part of key and can't be modified” exception

### ISSUE THREAD

**Issue by danny1972** [aspnet/EntityFramework6#378]
This issue was previously reported http://entityframework.codeplex.com/workitem/955 and acknowledged as a bug however there was no progress on a proper solution as there was a so called workaround.

The workaround however relies on being able to set the foreign key property rather than navigation property - this however doesn't work if the foreign object key is made up of a property which contains an IDENT as you don't know the value until the record is saved.

I can understand this error if the PK KEY was actually being changed but it's not.

**Comment by ajcvickers** [comment]
@danny1972 This looks related to http://entityframework.codeplex.com/workitem/2628, which is fixed in the EF 6.2 beta release. Can you try with the beta and see if your issue is already fixed?

**Comment by danny1972** [comment]
Apologies this version does correct this problem.   I did test with EF 6.2 beta before posting this but it still failed.  This morning I put together some sample code using 6.2 and it worked.  I've since found I was missing assigning the navigation property of the PK on the other object.  Thanks!
